version: "3.9"

services:
  node1:
    build: .
    container_name: raft-node1
    environment:
      # ID узла
      - NODE_ID=node1
      # Список пиров: id:URL внутри docker-сети
      - PEERS=node2:http://node2:8000,node3:http://node3:8000
    ports:
      # Пробрасываем наружу на хост
      - "8000:8000"
    networks:
      - raft-net

  node2:
    build: .
    container_name: raft-node2
    environment:
      - NODE_ID=node2
      - PEERS=node1:http://node1:8000,node3:http://node3:8000
    ports:
      - "8001:8000"
    networks:
      - raft-net

  node3:
    build: .
    container_name: raft-node3
    environment:
      - NODE_ID=node3
      - PEERS=node1:http://node1:8000,node2:http://node2:8000
    ports:
      - "8002:8000"
    networks:
      - raft-net

networks:
  raft-net:
    driver: bridge
